apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vtuber-playlist-tls
  namespace: vtuber
spec:
  secretName: vtuber-playlist-tls
  dnsNames:
    - playlist.incubator4.com
    - celine.playlist.incubator4.com
    - lilon.playlist.incubator4.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
