name: Deploy to Kubernetes

on:
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3.2
        with:
          version: "latest"
        id: install
      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy Setup Resource
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "vtuber"
          manifests: |
            manifests/ingressroute.yaml
            manifests/certificate.yaml
      - name: Deploy Web
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "vtuber"
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: "registry.cn-hangzhou.aliyuncs.com/incubator4/vtuber-playlist:sha-${{ github.sha }}"
